### ISSUE TITLE
updated version of tokenomics 

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_foundation#105]

**Comment by maximilianrang** [comment]
Working on it

**Comment by Sacha96** [comment]
@maximilianrang please advise on proceeding

**Comment by maximilianrang** [comment]
waiting for a design from ZQ on this. Then will make last updates and close

**Comment by Sacha96** [comment]
incredible! Thanks

**Comment by Sacha96** [comment]
@maximilianrang ??

**Comment by maximilianrang** [comment]
does ZQ have resources for this at the moment?
