### ISSUE TITLE
LEGAL - Links to 404 

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#106]
ThreeFold Definitions [info_foundation/docs/definitions/README.md](https://github.com/threefoldfoundation/info_foundation/blob/development/docs/definitions/README.md) has LEGAL definitions linking to 404
# Legal
- The Company
- The Product
- The Purchaser

**Comment by stelita** [comment]
Pierre contacted. Now waiting to hear from him. 

I would recommend removing the links and mention from the [README.md file](https://github.com/threefoldfoundation/info_foundation/blob/development/docs/definitions/README.md)

**Comment by sabrinasadik** [comment]
Deleted 'legal' definitions since these come back in the wiki under other sections
