### ISSUE TITLE
ThreeFold wallet links to 404

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#107]
There is no .md file for ThreeFold wallet under info_foundation/docs/definitions/ 

I created one and added an include to the explanation found at the [Token Wiki](https://wiki.grid.tf/wiki/tokens#/threefold_app).

Token wiki info is outdated, therefore, @sabrinasadik will help me updating with right info.

I assume that once info is updated at Token wiki it will automatically be revealed on this file since I'm using an include.

**Comment by sabrinasadik** [comment]
On it

**Comment by stelita** [comment]
https://www2.tokens.grid.tf/#/threefold_app Updated  - images not showing - working on it

**Comment by Sacha96** [comment]
@sabrinasadik please address and confirm during your sweep of the foundation wiki. Regards.

**Comment by sabrinasadik** [comment]
Is for token wiki - should not be in foundation wiki. @AdnanFatayerji @nbabenko who's on token wiki duty?

**Comment by Sacha96** [comment]
I'm reviewing the token wiki. Thought it may also be related to foundation wiki. Thanks for clarifying!

**Comment by AdnanFatayerji** [comment]
@stelita The Token wiki is being updated, the link works.
