### ISSUE TITLE
organize faq

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#11]
@yves https://threefoldfoundation.github.io/info_foundation/#/faq/home make nice overview page where we link to each faq, maybe better to have the faq's on separate docs, can still include

**Comment by yveskerwyn** [comment]
https://threefoldfoundation.github.io/info_foundation/#/faq/README

> Better overview now of all FAQs
> Next we will put each Q in separate doc

**Comment by yveskerwyn** [comment]
https://threefoldfoundation.github.io/info_foundation/#/faq/README

Each question now is a separate MD file
All questions (wording) have been reviewed

>> THE ANSWERS NEED SERIOUS REVIEW THOUGH
