### ISSUE TITLE
Updated .md file doesn't show on staging

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#111]
Last Friday 12th of April 2019 I updated and renamed it_capacity.md to ic_internet_capacity.md on [this .md file](https://github.com/threefoldfoundation/info_foundation/blob/development/docs/definitions/ic_Internet_capacity.md) however changes are not reflected in [wiki2](https://wiki2.grid.tf/wiki/foundation#/definitions/it_capacity)

**Comment by samtaggart** [comment]
@sabrinasadik Please check on this in your sweep of foundation wiki. Looks like the change is not working but do not know why.

**Comment by sabrinasadik** [comment]
Link works. 

PS. Please use - in stead of _ in .md file names since this sometimes leads to errors (not always, which is strange). Updated now - closing issue.
