### ISSUE TITLE
Tools under collaboration/_sidebar.md Links to 404 - relink tools wiki when wiki = live

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#135]
I'm working on collaboration and came across a 404 [here](https://github.com/threefoldfoundation/info_foundation/blob/development/docs/collaboration/tools.md)

https://github.com/threefoldfoundation/info_tools still not ready, therefore, "tools" will be removed from sidebar for now

Alternatively I can link it to [circles_tools](https://github.com/threefoldfoundation/info_foundation/blob/development/docs/collaboration/circles_tools.md) for now

Any feedback?

**Comment by samtaggart** [comment]
@stelita Please check on this. Thanks!

**Comment by Sacha96** [comment]
Hey there! Any progress on this issue? @samtaggart @stelita
