### ISSUE TITLE
autodeployment for the dev branch is not working

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_foundation#136]
Reproduce steps:
1. Edit any wiki file in github.
2. Wait 10 min 
3. Check the corresponding wiki page
Expected Result: wiki page updated according to the changes in github.
Actual Result: no changes deployed.

**Comment by VonSub** [comment]
this has been resolved already?

**Comment by samtaggart** [comment]
@VonSub Can you help to confirm if this has been resolved? I assume so. Can re-open if needed. Thanks brother.
