### ISSUE TITLE
Find out what Presentations to featured on our Wiki

### ISSUE THREAD

**Issue by lilianacarrillo** [threefoldfoundation/info_foundation#137]
Roel: not sure which presentation to feature on the wiki... most of them reside in archive.

**Comment by VonSub** [comment]
https://drive.google.com/drive/u/1/folders/1hE1KAPw3ekrnS_x7Ir56FWmK4s5OKahD

**Comment by lilianacarrillo** [comment]
I reopen the issue, as we have not selected the presentations yet.  
It is in waiting mode, waiting for the feedback of Kristof.

**Comment by samtaggart** [comment]
@sabrinasadik Since you are going through the foundation wiki can you please clarify what needs to happen with this issue, in your opinion?

**Comment by sabrinasadik** [comment]
Wiki's should feature the most recent / up to date presentations so that visitors can use these too:
TF Tech
TF Foundation
TF Love
3Bot

But I do think that these preso's belong in the seperate wiki's (tech wiki, love wiki, foundation wiki,...) and should not all be on the main foundation wiki.
