### ISSUE TITLE
Wiki side menu is too small and when closed text size changes

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#139]
Menu is too small and the text can't be read.

![Screenshot 2019-04-24 at 12 52 52](https://user-images.githubusercontent.com/36316337/56657440-ec295900-668f-11e9-92f7-1a74ab964229.png)

Text becomes bold when closing the side menu, making it difficult to read
![Screenshot 2019-04-24 at 12 52 57](https://user-images.githubusercontent.com/36316337/56657438-ec295900-668f-11e9-94a0-eaa69a59166b.png)

**Comment by lilianacarrillo** [comment]
Hi @stelita, my sidebar/menu is different: https://github.com/threefoldfoundation/info_foundation/issues/141

Is the size of the sidebar going to be fixed?
