### ISSUE TITLE
Move text under Projects to their respective wiki - use include here

### ISSUE THREAD

**Issue by lilianacarrillo** [threefoldfoundation/info_foundation#143]
The text under section projects has been added to the .md directly:
![image](https://user-images.githubusercontent.com/9121010/56809955-63e4b880-6835-11e9-9c61-be1e3a64eb9c.png)

It seems better to add the text directly on the correspondent wiki per project and then add it to the Foundation wiki with an include.  Here an example:
![image](https://user-images.githubusercontent.com/9121010/56810022-9393c080-6835-11e9-9c2a-f51669f2e808.png)

For the time being we wait till the includes work.  See issue:
https://github.com/threefoldtech/OpenPublish/issues/11

**Comment by samtaggart** [comment]
@VonSub Can you take a look at this? A little over my head, currently.

**Comment by Sacha96** [comment]
@VonSub can we close this issue??

**Comment by VonSub** [comment]
We can close it now the includes seem to be not working it needs to stay this way untill further notice.
