### ISSUE TITLE
Updated ThreeFold general presentation slide deck

### ISSUE THREAD

**Issue by AdnanFatayerji** [threefoldfoundation/info_foundation#146]
We need a new presentation deck to for investors and IEO platforms to link to

**Comment by weynandkuijpers** [comment]
Witte changed plan let’s rethink what need in the form of a presentation

**Comment by sabrinasadik** [comment]
Who's working on this preso?

**Comment by AdnanFatayerji** [comment]
Hey, Sabrina I am, it will be ready in a week.
