### ISSUE TITLE
move content from docs.grid.tf to wiki or gdrive

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#15]
check all repo's on https://docs.grid.tf/threefold/ 

- move all relevant to wiki grid/token, the foundation
- or move to gdrive if private or not meant for a wiki
- all org_repo's need to go to right gdrive location
- once move done remove repo's
- do same for https://docs.greenitglobe.com/ThreeFold

## DO NOT REMOVE

- itenv repo's
- make sure we don't overwrite newer content & we don't create duplication

**Comment by VonSub** [comment]
do we want to move data_team as well @despiegk
