### ISSUE TITLE
tech content needs to be on info_tech

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#16]
https://github.com/threefoldfoundation/info_tech/tree/master/docs

what needs to be in info_tech

- all content related to architecture or how to develop in ZOS & Jumpscale
    - use as much as possible includes from content from github

what not

- wallets/exchange/blockchain tech -> token wiki
- how to get started with grid, how to farm, how to use grid (is TF related)

**Comment by yveskerwyn** [comment]
Training was added: https://threefoldfoundation.github.io/info_tech/#/training/README

More to come...
