### ISSUE TITLE
HR section

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#17]
e.g. https://github.com/threefoldfoundation/info_foundation/blob/master/docs/org/hiring/hiring_ibiza.md

link to profiles on tech wiki

**Comment by VonSub** [comment]
No Profiles here yet:

https://threefoldfoundation.github.io/info_tech/#/HR/readme

Who owns the HR part?

**Comment by VonSub** [comment]
@despiegk who is owner of this?
