### ISSUE TITLE
Update team page 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_foundation#173]
On master https://github.com/threefoldfoundation/data_team/tree/master/team

This needs to be updated by everyone, so that we can add includes in all wiki's where we refer to the team.

**Comment by VonSub** [comment]
What exactly needs to happen here @sabrinasadik ?

**Comment by samtaggart** [comment]
@sabrinasadik Can you please clarify what you mean here?

**Comment by sabrinasadik** [comment]
The link in description is the master team repo. This needs to be updated by everyone, so that we can add includes in all wiki's where we refer to the team.

**Comment by samtaggart** [comment]
What needs to be updated exactly? @sabrinasadik

**Comment by sabrinasadik** [comment]
Who needs to be on the team page / everyone's bio needs to be reviewed - updated if needed.

**Comment by VonSub** [comment]
separate issue is already on the data_team repo for this.
