### ISSUE TITLE
see circles complete

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#18]
CHECK THAT BELOW INFO IS IN CIRCLES

## ThreeFold Token Promotion (Adnan)

- [ThreeFold Token Chatgroup @](https://chat.grid.tf/signup_user_complete/?id=wyn3qg6pe3gq7niy6w7yd3i6xy) : click on this one first before going to channel below
   - [news @](https://chat.grid.tf/tftokens/channels/town-square)
   - [chat @](https://chat.grid.tf/tftokens/channels/chat) : public chat about anything
- [Trello: https://trello.com/b/IqHW5DeD](https://trello.com/b/IqHW5DeD)
    - tbd: adnan
- [google drive home](https://drive.google.com/drive/folders/1_9XS7b_4aVWZ95nDdwIS_nEnkQxjKrnw)
    - [home page](https://docs.google.com/document/d/1SpZmeAgzeNxDPJTLnShd-NkkOREuJf0ItRHJCuDxE7Q/edit)
- [wiki](https://github.com/threefoldfoundation/info_foundation/blob/master/docs/circles/ThreeFold_Token_Promotion.md)

## ThreeFold Grid (Andreas)

- [ThreeFold Grid Chatgroup @](https://chat.grid.tf/signup_user_complete/?id=4ugqek6hyprc8qkrm9ifea9moo) : click on this one first before going to channel below
   - [news @](https://chat.grid.tf/tfgrid/channels/town-square)
   - [chat @](https://chat.grid.tf/tfgrid/channels/chat) : public chat about anything
- [Trello: https://trello.com/tf_grid](https://trello.com/b/FOZrIDOL)
    - [website roadmap @](https://trello.com/invite/b/qEqnHMKb/ab0e04a4c5ff7535d9a989f9d723a391/tfwebsiteroadmap)
    - [business development](https://docs.google.com/document/d/1B8Q_elx-J0ERj327e_u2qHoCiF1p2o-5KIQ_ERQZzJ4/edit)
    - [actions](https://trello.com/b/ZHo6yKPn/tfgridaction)
- [google drive home](https://drive.google.com/drive/folders/18pxbdERI3OGLgAjgkWhdK1bR5S3A9YtM)
    - [home page](https://docs.google.com/document/d/1B8Q_elx-J0ERj327e_u2qHoCiF1p2o-5KIQ_ERQZzJ4/edit)
- [wiki](https://github.com/threefoldfoundation/info_grid)
    
## ThreeFold Fund (Chris-)

- [ThreeFold Grid Chatgroup @](https://chat.grid.tf/signup_user_complete/?id=hnocjpbwb3fk8joxm6zenimc9o) : click on this one first before going to channel below
   - [news @](https://chat.grid.tf/tffund/channels/town-square)
   - [chat @](https://chat.grid.tf/tffund/channels/chat) : public chat about anything
- [Trello: https://trello.com/tf_fund](https://trello.com/tf_fund)
    - [website roadmap @](https://trello.com/invite/b/LRPeXGUl/f182413962369ac3cb9add0ebc1bfe3b/tffundwebsiteroadmap)
    - [actions](https://trello.com/b/tMIqBCvd/tffundactions)
- [google drive home](https://drive.google.com/drive/folders/1altPp-fX7FCjlugeMh3PGBXqF67kr9BE)
    - [home internal site](https://sites.google.com/s/1DvtpgqruZcCFWkUvyMKaXwBtn8_GQLQ2/p/129FumuiAc2T2UVn7JL6MzkFjyP8FzGwe/edit)
- [wiki](https://github.com/threefoldfoundation/info_fund)

## ThreeFold Tech (Kristof)

- [ThreeFold Grid Chatgroup @](https://chat.grid.tf/signup_user_complete/?id=h5duotxihb8ujkkjro3oqf798r) : click on this one first before going to channel below
   - [news @](https://chat.grid.tf/tftech/channels/town-square)
   - [chat @](https://chat.grid.tf/tftech/channels/chat) : public chat about anything
- [Trello: https://trello.com/tf_technology](https://trello.com/tf_technology)
   - [roadmap for archive features](https://trello.com/invite/b/ooL9NZnh/c56d9e74cb0a4ea845b8bf86e0b4a85a/roadmapfeaturesarchive)
   - [roadmap for compute features](https://trello.com/invite/b/5x1lVwdC/6f8e5c19490fb1e6edc3d974f4181d64/roadmapfeaturescompute)
   - [wiki roadmap @](https://trello.com/invite/b/SffGGj27/73448b868082e64e851db502ff4b895a/tftechwikiroadmap)
   - [actions](https://trello.com/b/gPzYrjTJ/tftechactions)
   - [urgent engineering](https://trello.com/b/zwgGSC5F/tftechengineeringurgent)
- [google drive home](https://drive.google.com/drive/folders/1AI_6hOe_lLZhqrkqXkYtQEj3mD6RFvQX)
    - [home page @](https://docs.google.com/document/d/12-12I5tCAlHYOa326Crk5e_94FCrcZq6dsX_daI-p9k/edit?usp=sharing)
- [wiki](https://github.com/threefoldfoundation/info_tech)

## ThreeFold Impact/Love (Olivia)

- [ThreeFold Grid Chatgroup @](https://chat.grid.tf/signup_user_complete/?id=h5duotxihb8ujkkjro3oqf798r) : click on this one first before going to channel below
   - [impact chat @](https://chat.grid.tf/threefold/channels/impact)
- [Trello : https://trello.com/tf_impact](https://trello.com/tf_impact)
   - [todo actions](https://trello.com/invite/b/yEz1Eobm/5c977d68675fccd42a2a00256a8b7cd2/tfimpactactions)
- [google drive home]()
    - [home page @]()
- wiki
    
## BetterToken (Dan)

only the items with @ are public

- [BetterToken Chatgroup @](https://chat.grid.tf/signup_user_complete/?id=us6s3sndc3dmirhc8qcpdezbky) : click on this one first before going to channel below
   - [news @](https://chat.grid.tf/bettertoken/channels/town-square)
   - [hardware selection for nodes @](https://chat.grid.tf/bettertoken/channels/hardware_selection)
   - [chat @](https://chat.grid.tf/bettertoken/channels/chat) : public chat about anything
- [Trello Team](https://trello.com/bettertoken)
  - [roadmap for website @](https://trello.com/invite/b/0HELF1TD/b566b744b5b6f7a81ba0a826b4f69a9e/websiteroadmap) : current version planned 1.1
  - [hardware selection for nodes @](https://trello.com/invite/b/sKXxq4yy/4209efd7ca159121db4d51497bfdcd89/hardwarechoice)
  - [support](https://trello.com/b/zC7PIDPH/support)
  - [tools_internal_it](https://trello.com/b/RNlnwU4c/toolsinternalit)
  - [tasks]() TODO, need to move from other board
  - [internal organization](https://trello.com/b/DT8UD9x8/btorganization)
- [google drive home](https://drive.google.com/drive/folders/1UOmjwXS2c9UOjS-7X4Bxp5xnqIZ3AaTE)

## Mazraa (Adnan)

- [Trello Team](https://trello.com/mazraa)
   - [actions](https://trello.com/b/UZscQzBW/mazraastories)
- [google drive home](https://drive.google.com/drive/folders/1QTYnHGuFKGqvlnP0gz5MlPB6DmvKURQB)
    - [home page](https://docs.google.com/document/d/1au3P6swKLxShuqbfxk3B5RpvsgBIylDQQ3Amaf2_bgM/edit)

## Our Community App (Marijke)

- [Trello Team](https://trello.com/ourcommunityapp)

## Codescalers (Nayer)

- [Trello Team](https://trello.com/codescalers)

**Comment by samtaggart** [comment]
@despiegk We are closing this issue because it is one year old. Please re-open if necessary and assign relevant parties. Thanks!
