### ISSUE TITLE
roadmap not readable

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#19]
https://threefoldfoundation.github.io/info_foundation/#/strategy/roadmap

is there a fix for it?

if too complex -> 1.0.1

**Comment by VonSub** [comment]
@ehab-hassan can you fix this?

@despiegk where are the source documents of these roadmaps? Maybe we should get them in the same style as the roadmap we feature on the website for more coherence.

**Comment by ehab-hassan** [comment]
I can prepare all as SVG images like threefold.me roadmap but I need to know who made the wikis so I can update

**Comment by VonSub** [comment]
@ehab-hassan post a link to the svg's here so I can reassign or check myself.

**Comment by ehab-hassan** [comment]
ok working in that now

**Comment by ehab-hassan** [comment]
[SVG.zip](https://github.com/threefoldfoundation/info_foundation/files/2184732/SVG.zip)
all images

**Comment by despiegk** [comment]
why svg images, I am trying to keep this as dynamic text, thats the full point.
I was the one assigned on this issue, so why did someone else work on it?

**Comment by despiegk** [comment]
we want the wiki to be dynamic, thats the full point, if we now make designed content we loose that feature!
