### ISSUE TITLE
Remove Wiki about TDE from the sidebar. 

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/info_foundation#202]
until we agree to frame and parameter, we need to remove public information about the TDE. We can make it available again after we update the Wiki.

**Comment by Vilnite** [comment]
Commented on Foundation wiki issue:
https://github.com/threefoldfoundation/info_foundation/issues/212#issuecomment-662910997

**Comment by Vilnite** [comment]
Outdated TDE info is still on main wiki - https://wiki.threefold.io/#/tdeoverview
