### ISSUE TITLE
New Wiki on Farming rewards calculation

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/info_foundation#203]
The Farming Wiki is missing information from the Tokens/Tokenomics section. We need a new Wiki on Farming rewards as this information is critical for onboarding farmers.

The explanations of CU and CPR needs to become parts of the new wiki on Farming rewards. They can then be removed from the sidebar along with their parent directory "Farming Concepts". Currently, this directory is incomplete and not critical.

**Comment by maximilianrang** [comment]
This should also include the mathematics behind difficulty.

**Comment by scottyeager** [comment]
Feel free to pull anything from my post [here](https://forum.threefold.io/t/threefold-tokenomics-discussion/328/80) that might be helpful.

**Comment by despiegk** [comment]
see changes made over weekend, think most of it already addressed

**Comment by maximilianrang** [comment]
added a new section on farming rewards and the according roadmap to make things a lot more clear for new farmers.
