### ISSUE TITLE
create video page

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#23]
1 sub page per video 
https://www.youtube.com/channel/UCKMNPuhs-8tHYfGd92krC8w/videos

explain what video is about

**Comment by VonSub** [comment]
Shall we add them to the info section. Sorted to date and mix them with other blog posts? To make the website become less static? @despiegk

**Comment by VonSub** [comment]
Will be done as soon as HUGO site is tested.

**Comment by yveskerwyn** [comment]
See: https://threefoldfoundation.github.io/info_foundation/#/videos/vienna

So I did it for two recordings from Vienna, which are together on one page.

Just copy approach for all other videos. 

For each event (or video):
- Create an `additional video-or-event-name.md`
- Optionally Update `/docs/videos/README.md`
- Update `/docs/videos/_sidebar.md`

**Comment by yveskerwyn** [comment]
Added some more video: https://threefoldfoundation.github.io/info_foundation/#/videos/README

Please take over from here...

**Comment by VonSub** [comment]
Thx @yveskerwyn I will see who can write up a few short descriptions about the videos.

**Comment by yveskerwyn** [comment]
I just added the video of @weynandkuijpers: https://threefoldfoundation.github.io/info_foundation/#/videos/tf_tech
