### ISSUE TITLE
Links do not work in wiki web_resources

### ISSUE THREAD

**Issue by JacqTrade** [threefoldfoundation/info_foundation#29]
ref : https://threefoldfoundation.github.io/info_foundation/#/web_resources 

 ThreeFold websites, discussed below:

_These links do not work :_ 

ThreeFold Foundation
ThreeFold Tokens
ThreeFold Farmers
ThreeFold Capacity
ThreeFold Radar

**Comment by ehab-hassan** [comment]
Links not working #39
