### ISSUE TITLE
tf_contributor_types.md : section about product development sounds more like an internal note then public documentaiton

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/info_foundation#36]
```

##  Product Development

Create the products which make all of this possible.

A website/wiki is a product !!!
It's something with version nr’s, it needs to be managed, controlled, improved.

Some of us are responsible for creating/delivering these products.

Each product is 100% managed on github, not trello !!! (exception community facing roadmap with community understandable messaging)
```

Shouldn't this section explain to the public what product development is about ?
Now it sounds more like an internal note then real documentation/explanation for a public audience

**Comment by samtaggart** [comment]
@zaibon Cannot find this. This issue is over a year old so it's possible this does not exist anymore but please help to confirm. Thanks!

**Comment by zaibon** [comment]
Closing this is fine I guess.  doesn't seems someone cared so I don't see a point to keep this open.
