### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#39]
On the page https://threefoldfoundation.github.io/info_foundation/#/web_resources

All links under "ThreeFold Websites" are not working:
ThreeFold Foundation
ThreeFold Tokens
ThreeFold Farmers
ThreeFold Capacity
ThreeFold Radar

Also, below:

ThreeFold Tokens
"Visit: tokens.threefold.me" is not working (https://tokens.threefold.me)

ThreeFold Farmers
"Visit: grid.threefold.me" is not working

On the page https://threefoldfoundation.github.io/info_tokens/#/?id=more-online-resources

Some links are not working:

More online resources:
- Token website: tftokens.com is not working - leads to https://threefold.me/tokens.html = 404
- Whitepaper (PDF): threefoldtoken.com/pdf/tf_whitepaper.pdf is not working - leads to https://threefold.me/pdf/tf_whitepaper.pdf = 404

**Comment by ehab-hassan** [comment]
I updated links for grid and tokens because it is now part of threefold.me 
I think GitHub repos for these links need to remove

**Comment by samaradel** [comment]
@stelita Whitepaper leads to  [`Whitepaper`](https://docs.google.com/document/d/16C3EKKBaK4_DyWFUcvdLnvDyN57h77e0Q1mWMpZL5vc/edit)not [https://threefold.me/pdf/tf_whitepaper.pdf](https://threefold.me/pdf/tf_whitepaper.pdf)
