### ISSUE TITLE
We need designs for social media

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#40]
As the TF Promotion team
We want all our Social Media banners updated
So that we can communicate more coherently.
@ehab-hassan Please prepare banners for:
- Facebook
- LinkedIn: Business & Personal
- Medium
- Twitter

Please also create designs for announcements (posts) for Instagram, and redesign the one for events and Community Calls for Facebook events.

Criteria:
Please use branding guidelines - "new style" background and fonts

Fonts:
Barlow Condensed Bold — for the titles
Nunito Sans (Regular and Black) — for body copy

Colors:
Slate black — #231f20
Deep Blue — #1247B3
Royal Blue — #266CEF
Jade Green — #29CC7A

**Comment by ehab-hassan** [comment]
[all-cover-brand.zip](https://github.com/threefoldfoundation/info_foundation/files/2244428/all-cover-brand.zip)
please check
