### ISSUE TITLE
Check if we can link to documents that are not in the summary.

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/info_foundation#44]
It seems linking to files that are not listed in the Summary is impossible (Or I am doing something wrong). It seems MDbook only created .HTMLs for the parts listed in the summary and all that are not are forgotten (at least when serving locally). Need to check when we "build" the book if this remains the same.. if that is the case we need to come up with something for some parts of the wiki.

Example links:

3.4 Grid/Concepts
6.1 Tech/Technolgy Same story as

5.1 Link to wallet section I also can't figure out

**Comment by hossnys** [comment]
SUMMARY.md file is the only source for files to be rendered and served by mdbook , but as workaround for this you can use include as and option for adding .md files content to your files served in summary.md 
```
[Farming Rules](farming_token_geration_rules.md){{#include farming_token_geration_rules.md}}

```
and will show like this 
![Screenshot from 2020-04-12 10-08-22](https://user-images.githubusercontent.com/26298009/79104760-81c16b00-7d6f-11ea-8f1c-06c583da7ece.png)
you can see it here also : http://157.245.87.227:3000/docs/grid/concepts/grid_concepts.html

**Comment by hossnys** [comment]
also there is an issue opened for same situation on mdbook repo here https://github.com/rust-lang/mdBook/issues/702
