### ISSUE TITLE
Whitepaper - Hyperlink on abstract is not working (404)

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#48]
While reviewing the Whitepaper (clicking the link on the menu of the Website https://threefold.me/ - https://docs.google.com/document/d/16C3EKKBaK4_DyWFUcvdLnvDyN57h77e0Q1mWMpZL5vc/edit#) 
I found that a link not working  on the last line of the abstract, on page 2
- "ThreeFold’s Operating System allows Farmers to deliver Internet/IT capacity to the Grid using up to 10 times less energy than traditional data centers" 

the text "10 times less energy " is hyperlinked, however, the link takes you to a 404 (https://threefold.me/information/10-times-power-savings/)

**Comment by despiegk** [comment]
move latest whitepaper to markdown & put on wiki
ask Kds to review

**Comment by stelita** [comment]
Will use macros and add it to Foundation wiki

**Comment by Sacha96** [comment]
@stelita this issue seems pretty old, is it still relevant? If not we can close it.
