### ISSUE TITLE
Flyer for RDC event

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#53]
@ehab-hassan please create 2 flyers for an event that will take place two consecutive days. Use same colors/branding than in the website, similar to the social media headers you did, but the same size used for TF meets events.

Title of the events: Responsible Digital Currencies: The Dawn of Digital Ethics

Date: 13th of September / 14th of September

Location: Midori Boat

**Comment by ehab-hassan** [comment]
![the dawn of digital ethics-events](https://user-images.githubusercontent.com/10484295/44990364-15766700-af91-11e8-812f-847f5b884fb4.jpg)
![responsible_digital_currencies_event](https://user-images.githubusercontent.com/10484295/44990365-15766700-af91-11e8-982e-ce2d59d269e4.jpg)
