### ISSUE TITLE
tokenomics

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#60]
- 4billion
- 10% is min aim for the TF Foundation, stress that 50% of the planet has no capacity yet
- 0.5% marketshare, visualize what it means
- link to simulator
- some screenshots
- link it back to the token of internet page, with banner in page

**Comment by andhartl** [comment]
doc is ready for review: https://github.com/threefoldfoundation/info_threefold/blob/development/src/token/new_tokenomics/tokenomics%20updated.md

**Comment by andhartl** [comment]
@VonSub can you please add a Tokenomics block above how to buy tft and linkt o the above doc?

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/18591016/80598217-4ee2cc80-8a29-11ea-99d8-495833a479b3.png">

**Comment by andhartl** [comment]
make it "ThreeFold Tokenomics. The Projects Potential - click to learn more"

**Comment by andhartl** [comment]
text for block: The ThreeFold Grid has the potential to gain a significant share in todays public cloud market. Click here to learn more

**Comment by andhartl** [comment]
@Sacha96 can you please help here?

**Comment by andhartl** [comment]
@despiegk pls check if content is ok for you

**Comment by andhartl** [comment]
working link: https://github.com/threefoldfoundation/info_threefold/blob/development/src/token/new_tokenomics/tokenomics_updated.md

**Comment by Sacha96** [comment]
pushed changes on https://www2.threefold.io/token.html

<img width="1440" alt="Screenshot 2020-04-30 at 15 56 47" src="https://user-images.githubusercontent.com/54844940/80719056-3511ba00-8afb-11ea-99bb-93e176634b83.png">

**Comment by Sacha96** [comment]
@andhartl @despiegk

**Comment by Sacha96** [comment]
Github links provided aren't working. In any case, lets make sure updated tokenomics enter wiki @andhartl @maximilianrang then ping me with rwiki link for me to add to https://www2.threefold.io/token.html. Thanks!

**Comment by Sacha96** [comment]
@andhartl @maximilianrang what's the status?

**Comment by Sacha96** [comment]
I think we're good here, i'm closing the story.
