### ISSUE TITLE
token overview

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#61]
info about nr of tokens, ...

distribution to the projects

**Comment by andhartl** [comment]
here is the link to the doc
https://github.com/threefoldfoundation/info_threefold/blob/development/src/token/token%20overview/token_overview.md

**Comment by andhartl** [comment]
done

**Comment by andhartl** [comment]
@despiegk can you pls check if content ok? where do you want to put it? token section?
