### ISSUE TITLE
Info_foundation generated md files has a lot of broken links

### ISSUE THREAD

**Issue by ahmadnazih** [threefoldfoundation/info_foundation#69]
- circles:/sandbox/code/github/threefoldfoundation/info_foundation/docs/collaboration/circles.md(problem with link:[](readme.md ':/circles/readme.md'))

**Comment by ahmadnazih** [comment]
- **/info_foundation/docs/contributors/tf_team.md** : problem with link:[ThreeFold Foundation](/contributors/tf_companies.md) &  problem with link:[TFTech=BetterToken](tftech/tftech.md) & problem with link:[BetterToken]((tftech/tftech.md)

- **/info_foundation/docs/contributors/tftech/Andreas_Hartl.md** : roblem with link:[my personal data on gogs](https://docs.greenitglobe.com/ThreeFold/home/src/master/team/kristof_de_spiegeleer.md)

- /info_foundation/docs/contributors/tftech/Joris **Vermeulen.m** :  problem with link:![]()

- **/info_foundation/docs/contributors/tftech/Yves_Kerwyn.md** : problem with link:[@yveskerwyn](skype:yveskerwyn?call)

- **/info_foundation/docs/definitions/_sidebar.md**: problem with link:[ThreeFold Wallet](definitions/threefold_wallet.md)

- **/info_foundation/docs/definitions/definitions.md**: problem with link:[ThreeFold Wallet](definitions/threefold_wallet.md) & problem with link:[The Company](sub/the_company.md ':include')  & 
problem with link:[The Product](sub/the_product.md ':include') &  problem with link:[The Purchaser](sub/the_purchaser.md ':include')

**Comment by ahmadnazih** [comment]
- **/info_foundation/docs/definitions/README.md**: problem with link:[ThreeFold Wallet](/definitions/threefold_wallet.md)

- **/info_foundation/docs/itenv/wiki_pages_other_toc.md**: problem with link:[http://tools_wiki.threefold.me](http://tools_wiki.threefold.me)

- **info_foundation/docs/legal/buy_tfts_from_farmer_example_contract.md**:  problem with link:[Farmer]  (the “Company”)

- **info_foundation/docs/legal/definitions.md**: problem with link:[ThreeFold Wallet](../definitions/threefold_wallet.md)

- **/info_foundation/docs/news/web_new.md**:  problem with link:[threefold foundation](http://www2.threefold.me) & problem with link:[threefold grid](http://grid.threefold.me) & problem with link:[threefold tokens](http://tokens.threefold.me)

- **/info_foundation/docs/org/hiring/hiring_ibiza.md**: 
```python
ERROR IN MACRO*** TODO: *1 ***
macro:
include

-

**Comment by weynandkuijpers** [comment]
Will update today - thank you for the inventory
