### ISSUE TITLE
Web Resources - 'Foundation' content upgrade

### ISSUE THREAD

**Issue by lilianacarrillo** [threefoldfoundation/info_foundation#79]
From the principle that Less is More, I suggest the following change: merge content.  

Instead of having 2 pages for the web resources related to the Foundation, have only 1 page.

Instead of having this 2 pages:
https://threefoldfoundation.github.io/info_foundation/#/web_resources/wiki_foundation
and
https://threefoldfoundation.github.io/info_foundation/#/web_resources/website_foundation

Only have one page for the foundation, something like this:
https://threefoldfoundation.github.io/info_foundation/#/web_resources/foundation

With following content:

(Title) ThreeFold Foundation Web Resources

Right now you are actually on the ThreeFold Foundation Wiki pages: wiki.threefold.io

For feedback, please create issues in the following GitHub repository: https://github.com/threefoldfoundation/info_foundation/issues

Or contribute directly in the develop branch: https://github.com/threefoldfoundation/info_foundation

Visit the website: www.threefold.io 

Content of the website:

- Everything related to the ThreeFold Foundation
- Team, ambassadors and community
- General information on the project
- Articles
- Links to resources
- Mission and values
- Links to other websites & wiki sites

**Comment by nbabenko** [comment]
agree that this would be a good idea

**Comment by lilianacarrillo** [comment]
Perfect, I have simplified this and created only one page visible here: https://github.com/threefoldfoundation/info_foundation/blob/development/docs/web_resources/foundation.md

Summary: wiki_foundation.md and website_foundation.md have been merged into one foundation.md

The content has been adapted as visually this one below was better (it will be visible on wiki2 after this issue is resolved https://github.com/threefoldfoundation/info_foundation/issues/85):

ThreeFold Foundation Wiki
Right now you are on the ThreeFold Foundation Wiki pages: wiki.threefold.io

For feedback on this wiki, please create issues in the following GitHub repository: https://github.com/threefoldfoundation/info_foundation/issues

Or contribute directly to this wiki in the develop branch: https://github.com/threefoldfoundation/info_foundation

ThreeFold Foundation Website
You can also visit the website: www.threefold.io

Content of the website:

Everything related to the ThreeFold Foundation
Team, ambassadors and community
General information on the project
Articles
Links to resources
Mission and values
Links to the other websites & wiki sites
At anytime feel free to post issues on our github repository about the Foundation website if you think something is unclear or missing: https://github.com/threefoldfoundation/www_threefold.io/issues

Or contribute directly to improve the Foundation website in the develop branch: https://github.com/threefoldfoundation/www_threefold.io
