### ISSUE TITLE
Enable autodeployment for the wiki

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_foundation#83]
Both for production and wiki2

**Comment by PeterNashaat** [comment]
The autodeployment is working
![image](https://user-images.githubusercontent.com/13523434/55862572-0257f500-5b79-11e9-9682-898d72691797.png)

and the last push was https://github.com/threefoldfoundation/info_foundation/commit/fc5b32b6a8a80ef2f916159ebe5617203e2bf04f

to add  _presentations_toc.md file to README push this line to master branch

- [ _presentations_toc.md](https://github.com/threefoldfoundation/info_foundation/blob/development/docs/presentations/_presentations_toc.md)

```
- [name you want](https://github.com/threefoldfoundation/info_foundation/blob/development/docs/presentations/_presentations_toc.md)
```

**Comment by PeterNashaat** [comment]
url : http://foundation.grid.tf
development url : http://www2.foundation.grid.tf
