### ISSUE TITLE
wiki2 autodeployment is not working

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/info_foundation#85]
Links to check: 
https://wiki2.grid.tf/wiki/foundation#/

https://github.com/threefoldfoundation/info_foundation/tree/development/docs

See "test" in the end.

**Comment by nbabenko** [comment]
still not working

**Comment by nbabenko** [comment]
still not working...

**Comment by abom** [comment]
Should be resolved by the new publishing platform.
