### ISSUE TITLE
Threefold Unmanaged and Managed Capacity are empty

### ISSUE THREAD

**Issue by stelita** [threefoldfoundation/info_foundation#89]
I found 2 .md files who are empty

https://github.com/threefoldfoundation/info_foundation/blob/development/docs/definitions/threefold_unmanaged_capacity.md

Managed Capacity is also empty 
https://github.com/threefoldfoundation/info_foundation/blob/development/docs/definitions/threefold_managed_capacity.md

**Comment by andhartl** [comment]
hm. we have it in grid wiki. not sure if needed in foundation as very specific and long files

**Comment by stelita** [comment]
Can I delete the files from Foundation wiki?
