### ISSUE TITLE
move blogs from gdrive

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_foundation#9]
https://drive.google.com/drive/folders/0B_dXq0dA11-sVFk3LWVrWXlYMFk

- move content
- if found on wiki, remove from source, so we don't have doubles

**Comment by despiegk** [comment]
also https://drive.google.com/drive/folders/0B_dXq0dA11-sbG0zNC15aXdJSXM

**Comment by despiegk** [comment]
also https://drive.google.com/drive/folders/0B_dXq0dA11-sblg4cTR3Si0wc3M

**Comment by despiegk** [comment]
also https://drive.google.com/drive/folders/0B_dXq0dA11-sOWI3aGJhWWs1NUk

**Comment by despiegk** [comment]
also https://drive.google.com/drive/folders/0B_dXq0dA11-sckR6SG9uQ0M1U1k

**Comment by despiegk** [comment]
don't forget to remove the source, so it only exists once

**Comment by yveskerwyn** [comment]
all done, everything is in _archive. we could delete it there too, for the blogs I added a link to the new source in info_foundation
