### ISSUE TITLE
Web Resources - 'Tech' content upgrade

### ISSUE THREAD

**Issue by lilianacarrillo** [threefoldfoundation/info_foundation#90]
There is only content about the wiki:
ThreeFold Tech Wiki Visit: [Technology](https://wiki.grid.tf/wiki/tech#/)

There is no content about the website or github.  It needs to be updated.

Following the new merged structure in Web Resources, I will only create one page for 'Tech' like this: https://threefoldfoundation.github.io/info_foundation/#/web_resources/tech

**Comment by lilianacarrillo** [comment]
I am needing support to complete this task.  I do not find the information needed.
The improvements are here: https://github.com/threefoldfoundation/info_foundation/blob/development/docs/web_resources/tech.md

Help needed:

1. What is our github to contribute to the wiki.  
This one? https://github.com/threefoldtech/info_tftech 
Or this one? https://github.com/threefoldtech

2. What is our github to contribute to the Tech website?

**Comment by lilianacarrillo** [comment]
Hello @stelita, I hear from @VonSub that you have been arranging information about Tech.
Could you support me with some information I need?  Please read here above.  Thanks in advance!

**Comment by stelita** [comment]
Here! https://docs.google.com/document/d/1mTN68DsHaWydHcqfwnJVhWAkswHhkoSvXeq-xDPCGIA/edit#heading=h.1ly4231nlti8

**Comment by lilianacarrillo** [comment]
The help I need is not in that document.  This is what I need to know:

What is our github to contribute to the wiki.
This one? https://github.com/threefoldtech/info_tftech
Or this one? https://github.com/threefoldtech

What is our github to contribute to the Tech website?

**Comment by lilianacarrillo** [comment]
Cleared out.  Thanks @VonSub
