### ISSUE TITLE
Compare WebResources Partners page and Section Projects - Merge?

### ISSUE THREAD

**Issue by lilianacarrillo** [threefoldfoundation/info_foundation#95]
On the wiki there is a page for Partners under Web Resources: 
https://wiki2.grid.tf/wiki/foundation#/web_resources/website_partners

@nbabenko has created several files under a new section called Projects, and some names are repeated.  Check this.  Needs to be merged? or 2 different sections?

**Comment by lilianacarrillo** [comment]
Under the new files related to Projects I see some that are called Partners in the TF Ecosystem file: https://docs.google.com/document/d/1TiuVr9xhoAiAqZD0GTMvxphS8oY2CkjM3V2iWIS-p1M/edit#

How do we organize this?

**Comment by lilianacarrillo** [comment]
Hi @nbabenko , Web Resources is quite clean now.  But I still need support about this issue.

These are the options I see regarding the improvement of Partners and Projects:

1. Delete the page website_partners under Web Resources and only leave the section Projects with all the files per project.
2. Keep the page website_partners and align it with the content of our GDocs TF Ecosystem.  Check the projects and add them to the section projects. Align Projects and Partners.
3. Delete website_partners and add a section apart called Partners as on GDocs TF Ecosystem.  Align Partners as on GDocs TF Ecosystem.

**Comment by nbabenko** [comment]
As far as I know, all partners already mentioned in ecosystem document, or if anything missing, let me know I will add it there. So it would more fit for option #1

**Comment by lilianacarrillo** [comment]
Hi @nbabenko , 

The following partners/projects mention on web_partners under WebResources are missing in the new section Projects.  There are no .md files for these under Projects:
- Hewlett Packard Enterprise
- Solidaridad
- Edge Cloud Afrika
- Bancadati
- Green Edge Cloud
- Safe City
- GIG Europe
- Individual Farmers
- Mobicage

**Comment by lilianacarrillo** [comment]
Dear team, I have added the text of all projects mentioned on the GDoc TF-Ecosystem: https://docs.google.com/document/d/1TiuVr9xhoAiAqZD0GTMvxphS8oY2CkjM3V2iWIS-p1M/edit#

I see on that document other sections:  Partners, Application Solutions, Grid Farming/Cooperative Partnership, and ThreeFold Chapters.

HPE
ATWGreen
Incubaid
CodeScalers
Kleos
Safe City
Jimber
Harvested.io
FreeFlowPages
OpenMeeting
Solidaridad
Mazraa Cooperative
Bettertoken BVBA
Bancadati
Green Edge Cloud
Digital Energy

**Comment by lilianacarrillo** [comment]
Hi @nbabenko,
We are almost there with all the content of the ecosystem.  😁  I am very happy for this.  I would like your advice regarding an idea that I have.  

I see that you created several .md files under Projects that are considered something else in our GDoc TF_Ecosystem.  They are considered Partners, Applications solutions and something else.  I have not filled those .md files yet as I would like to place them in the right section.

The existing section is Projects.

Possible solutions I see:

1.  Open a new section called Partners and move those .md under that section?  To continue following the structure of our GDoc TF_Ecosystem.  Keep section Projects with the stuff under Projects on that GDoc TF_Ecosystem.

2.  Change the title of the Projects section to 'Partners and Projects' and add everything there, all the information under GDoc TF_Ecosystem.

**Comment by lilianacarrillo** [comment]
Thanks @nbabenko for your support.  I am closing this issue as you have supported me to decide on this.  Option 2 has been chosen.
